spring:
  application:
    name: madang
  datasource:
    url: jdbc:mariadb://localhost/board_1
    username: root
    password: green502

# 주석은 똑같다.
mybatis:
  mapper-locations: mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true