spring:
  application:
    name: madang
  datasource:
    url: jdbc:mariadb://localhost/madang_spring
    username: root
    password: green502

# 주석은 똑같다.
mybatis:
  mapper-locations: mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    default-model-expand-depth: 2
    default-models-expand-depth: -1
    path: /swagger